development:
  adapter: postgresql
  database: mydb_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: mydb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mydb_production
  pool: 5
  timeout: 5000
